### ISSUE TITLE
can you delete  "block(self, nil);"

### ISSUE THREAD

**Issue by codesourse** [Tricertops/Block-KVO#38]
- (void)observeNotification:(NSString *)name fromObject:(id)object withBlock:(MTKBlockNotify)block {

    // Invoke manually for the first time.
    block(self, nil);

    __weak typeof(self) weakSelf = self;

    id internalObserver = [[NSNotificationCenter defaultCenter] addObserverForName:name
                                                                            object:object
                                                                             queue:[NSOperationQueue currentQueue]
                                                                        usingBlock:^(NSNotification *notification) {
                                                                            if (notification!=nil) {
                                                                               block(weakSelf, notification);
                                                                            }
                                                                        }];

    [[self mtk_notificationBlockObservers] addObject:internalObserver];

}

we don't need Invoking manually for the first time.

**Comment by Tricertops** [comment]
Fork the repository and edit as you wish.
