### ISSUE TITLE
Expose change dictionary for observing collections

### ISSUE THREAD

**Issue by warpling** [Tricertops/Block-KVO#42]
Currently the KVO block doesn't pass in the change dictionary making it hard to disambiguate if a change on a collection was caused by an insertion, deletion, change, etc.

(Thank you for this library!)

**Comment by Tricertops** [comment]
Did you try [this method](https://github.com/Tricertops/Block-KVO/blob/master/Sources/NSObject%2BMTKObserving.h#L136)?

```objc
- (void)observeRelationship:(NSString *)keyPath
                changeBlock:(MTKBlockChange)changeBlock
             insertionBlock:(MTKBlockInsert)insertionBlock
               removalBlock:(MTKBlockRemove)removalBlock
           replacementBlock:(MTKBlockReplace)replacementBlock;
```

**Comment by warpling** [comment]
Missed that! Thanks :)
