### ISSUE TITLE
Obscure retain issue in -removeAllObservationsOfObject:

### ISSUE THREAD

**Issue by JamesBucanek** [Tricertops/Block-KVO#43]
First let me say that I recently integrated Block-KVO into my project and been very happy with it. I researched a number of block-based KVO solutions, and this one was one of the few that takes retain cycles seriously. There are a number of design issues I might quibble with, but I can't fault its performance.

Now onto the problem.

I discovered a rather obscure memory management issue with `-removeAllObservationsOfObject:`. Here's the scenario that causes the problem:

Object `D`: Data model object
Object `C1`: A controller
Object `C2`: Another controller

`C1` and `C2` both register "foreign" observations blocks with the data model object, like this:
```
[self observeObject:D property:@"repositoryReference" withBlock: ... ];
```

I have cases in my code where the data model object might get replaced, so I have methods that encapsulate the releasing and setting of said object in the `C2` view controller. When adopting Block-KVO, I added code to detach all observations, thusly:
```
- (void)forgetDataModel {
    [self removeAllObservationsOfObject:self.representedObject];
    self.representedObject = nil;
    ...
```

Here's where it goes south.

1. During a window close, the code to forget the data model in `C2` gets called.
2. `C2` sends `[C2 removeAllObservationsOfObject:D]`.
3. `C2` then sends `[D mtk_removeAllObservationsForOwner:C2]`
4. `D` iterates through its observer dictionary (by keyPath) and sends itself `-mtk_removeObservationsForOwner:keyPath:` for each key.
5. In `-mtk_removeObservationsForOwner:keyPath:` `D` finds the observer for `C2`, detaches it, and removes it from the set of observers for that keyPath.
6. `D` returns to the loop and iterates to the next collection of observers.
7. In the next `-mtk_removeObservationsForOwner:forKeyPath:` call, a "sent -retain message to zombie object" exception gets thrown.

What happened was this: the observer block for `C2` _just happened_ to contain the last strong reference to the controller `C1`. When `C2`'s observer was released, `C1` got deallocated. Afterwards, the loop in `-mtk_removeAllObservationsForOwner:` continues, but it soon iterates through to the (now detached) observer for `C1`. The `owner` of the observer no longer exists, but ARC sends it a `-retain` when it calls the property getter in the `if (observer.owner == owner)` conditional, and then bad things happen.

It took me awhile to figure how why this is happening. It's an impedance mismatch between the way `-removeAllObservationsOfObject:` works and how most of the internal, swizzled-dealloc-triggered, methods work. The high-level `-removeAllObservationsOfObject:` detaches the observers and removes them from the collection of observers. The `-dealloc`-triggered methods simply `-detach` the observer, and expect the observer objects to get released en mass along with the object.

Pondering the problem, I think that `-removeAllObservationsOfObject:` (and related methods) needs to deal with the possibility of detached-and-released owners in the observer pool that are still associated with the object. I considered other solutions, but I think this is most direct fix, albeit not the cleanest.

The problem is that (apparently) all property getters under ARC, synthesized or otherwise, get a `-retain` & `-autorelease` before returning. So it's impossible for the category to get the observer's `owner` property without indirectly retaining it. My simple solution was to add an ownership test method that avoids the gratuitous `-retain`:

```
@implementation MTKObserver
...
- (BOOL)isOwnedBy:(__unsafe_unretained id)someObject
{
	return _owner == someObject;
}
```

Now it's safe to write:
```
- (void)mtk_removeObservationsForOwner:(id)owner keyPath:(NSString *)keyPath {
    NSMutableSet *observersForKeyPath = [self mtk_keyPathBlockObservers][keyPath];
    for (MTKObserver *observer in [observersForKeyPath copy]) {
        if ([observer isOwnedBy:owner]) {
            [observer detach];
            [observersForKeyPath removeObject:observer];
...
```

If you think this all makes sense, I'll implement it for real and send a pull request.

**Comment by Tricertops** [comment]
Thanks for your time for reporting this issue. It took me some time to visualize your setup, but I think I got it. That single `assign` property was just waiting there to cause troubles 😆 Unfortunatelly, it’s not possible to use `weak` in this case.

If I understand your proposed solution, it manipulates with a reference to potentially deallocated object. Is that right? In that case, it might _just happen_ to work and we should try some other solution.

**Comment by Tricertops** [comment]
Here is my proposed solution:

```objc
NSMutableSet *observersForOwnerForKeyPath = [[NSMutableSet alloc] init];
for (MTKObserver *observer in observersForKeyPath) {
    if (observer.owner == owner) {
        [observersForOwnerForKeyPath addObject:observer];
    }
}
for (MTKObserver *observer in observersForOwnerForKeyPath) {
    [observer detach];
    [observersForKeyPath removeObject:observer];
}
```

The removal now happens in two phases:
  1. Collect observers for given owner. Here it accesses the `.owner` property.
  2. Detaches all the collected observers. Here, one of the owners can get deallocated, but we no longer access `.owner` property.

Could you try the [latest commit](https://github.com/Tricertops/Block-KVO/commit/135a8c6f130fc118d8252724163161ac0935c936) with this fix?

**Comment by JamesBucanek** [comment]
I had some time to think about this, and your solution still won't work.

The problem is that when `-mtk_removeObservationsForOwner:keyPath:` gets invoked, any number of observation owners could have been deallocated. So no use of the `observer.owner` property is safe because ARC will issue a `retain` + `autorelease` to the owner object, and if the owner object has already been deallocated, bad things will happen. So there is no code that uses `observer.owner` which is safe here.

The basic problem is this, and it leads to two bugs: A "foreign" observer (`F`) can create an observation object on some arbitrary data object (`D`). Later, the observer object `F` can be released and deallocated. During deallocation, it will `-detach` its observation objects. But unless `D` is also deallocated, that observation object will still be attached to `D` ... forever.

Bug #1 is the one I already explained. So-called "foreign" observers create observation objects associated with `D` which have an owner property that might later refer to a deallocated object. In my program, this happened during the deallocation of another observer, but in retrospect this could have happened at any time. Once this occurs, any message set to the `owner` property is bad.

(This never happens for objects observing themselves, for obvious reasons.)

Bug #2 is that this creates a memory leak. If you have a long lived data model object, and a slew of transient observers (control and view objects, which is my design), the data model object will accumulate an unbounded number of detached observation objects. As each observer is deallocated, it detaches its observation object, but doesn't remove it from the observer.

(Currently, the only way to avoid this is to have each observer deliberately send `-removeAllObservationsOfObject:`, which not only detaches the observation object, but also removes it from the observed object.)

Another way of fixing this is to have the detach-on-dealloc code (in `-initWithTarget:keyPath:owner:` also `nil` the reference to `owner`. This would create a third state for an observation object:
1. attached with owner
2. detached with owner
3. detached with no owner
Now uses of `observer.owner` are safe. The nil value could also be used somewhere to detect observation objects that no longer have an owner so they can be incrementally discarded.

**Comment by JamesBucanek** [comment]
Another solution would be to have the registration code make a distinction between a "self" observation block (`- (void)observeProperty:withBlock:` et. al.) and a "foreign" observation (`-observeObject:property:withBlock:` et. al.).

The "foreign" observations could register "on-dealloc" code that both detached and removed the observer from the observed object, while the "self" observations could get away with just detaching the observation object (since it knows they will be soon discarded along with the object).

**Comment by JamesBucanek** [comment]
I created a simple unit test for this issue.

```
- (void)testToDemonstrateIssue43 {
	MTKTestingObject *object = [MTKTestingObject new];
	@autoreleasepool {
		// A short-lived foreign obsever
		MTKTestingObject *foreign = [MTKTestingObject new];
		[foreign observeObject:object property:@keypath(object,title) withBlock:^(id self, id object, id oldValue, id newValue) {}];
		// At end of autorelasepool block, foreign will be deallocated, but will leave its observation object attached to |object|
	}
	// Sometime later, a new object observes a property
	MTKTestingObject *foreign2 = [MTKTestingObject new];
	[foreign2 observeObject:object property:@keypath(object,title) withBlock:^(id self, id object, id oldValue, id newValue) {}];
}
```
Now edit the Test scheme settings by turning on Zombie objects under diagnostics.

Run the unit tests:
```
Test Suite 'Selected tests' started at 2016-12-16 11:30:19.150
Test Suite 'Tests.xctest' started at 2016-12-16 11:30:19.151
Test Suite 'BlockObservingTests' started at 2016-12-16 11:30:19.152
Test Case '-[BlockObservingTests testToDemonstrateIssue43]' started.
2016-12-16 11:30:19.153 xctest[2447:86245] *** -[MTKTestingObject retain]: message sent to deallocated instance 0x7ff448509af0
```

**Comment by Tricertops** [comment]
I see the problems now. The bad news is that the whole deallocation thing is broken. Working on that ☹️

**Comment by Tricertops** [comment]
First of all, thank you for investigating this issue and for writing a test. I looked into this and I fixed several bugs in latest commits:

  1. Deallocating observed object actually removes the observers from associated dictionary.
  2. Invocation of deallocation blocks handles recursive mutations.
  3. Test for deallocation actually tests the behavior.
  4. Observations are removed also when foreign owner deallocates.

Your test is now included in the test suite (little modified) and it is passing. Please, try the latest commit and verify that it works for you.

**Comment by Tricertops** [comment]
It’s obvious from this that I don’t actually use foreign observations much 😄 I usually store data objects as properties of controllers and I always observe `self`.

```objc
[self observeProperty:@keypath(self, dataObject.property) withBlock: ...];
```

**Comment by JamesBucanek** [comment]
Thanks, I'll pull down the new version and try it out.

I could tell that this project was mostly focused on self observation, but I have a few situations where I have a child controller or view object that observes changes in a parent controller, and might not have a property reference to it.

**Comment by JamesBucanek** [comment]
It doesn't crash!
