### ISSUE TITLE
Initial value detection

### ISSUE THREAD

**Issue by JamesBucanek** [Tricertops/Block-KVO#45]
In continuing to use Block-KVO, the issue of trying to determine if the observer block is being invoked with the initial value or an actual change keeps coming up. This is particularly problematic with property values that can be nil.

It suddenly occurred to me that there's an unambiguous fix for this. Instead of invoking the observer blocks with an old value of nil `block(self,nil,initialValue)` during setup, invoke it with the same value for both parameters: `block(self,initialValue,initialValue)`.

The block can then easily, cheaply, and definitively, determine if the block is being invoked with the initial value:

```
[self observeProperty:@"representedObject.schedule"
			withBlock:^(typeof(self) self, id oldValue, id newValue) {
	if (oldValue==newValue) {
		// iff initial value
	} else {
		// iff value change
		}
	}
}];
```

The bad news is that this breaks code that is assuming `oldValue` will be `nil` on the initial call.

**Comment by JamesBucanek** [comment]
Never mind. I forgot that `-isEqual:` is also involved, which means `oldValue==newValue` could be true at the same time that `[oldValue isEqual:newValue]` could be false.

**Comment by JamesBucanek** [comment]
I closed this, thinking that'd I'd missed something obvious, but the more I think about it the more I'm convinced this will always work.

Because of the equality test performed by the observation object, the `oldValue` and `newValue` parameters can never be identical during a change notification.

**Comment by Tricertops** [comment]
Your suggestion is smart! It builds on top of an existing behavior – equal values are not reported as changes.

I agree with your concern that existing code that assumes `oldValue` is initially nil, would break. Breaking behavior would require to increase version to 3.0. Anyone updating from 2.x to 3.0 will likely read the release notes.

**Comment by Tricertops** [comment]
I created version `v2.3` with latest changes (before your suggested behavior change) and also `v3.0` with only this behavior change.

**Comment by JamesBucanek** [comment]
Glad I could contribute.
