### ISSUE TITLE
Two-way binding causing infinite loop

### ISSUE THREAD

**Issue by emobtech** [Tricertops/Block-KVO#46]
Hi,

The recursion-safe for two-way binding caught my attention, but unfortunately it's not working. My code runs in loop when the second binding is reached.

[self map:@keypath(self.operationType) to:@keypath(self.headerView.operationType) null:nil];
[self map:@keypath(self.headerView.operationType) to:@keypath(self.operationType) null:nil];

Any advice?

Regards,

**Comment by Tricertops** [comment]
Hi, this feature should work thanks to [this line](https://github.com/Tricertops/Block-KVO/blob/master/Sources/MTKObserver.m#L167), which avoids observation of equal values.

Does any of your properties have custom getter or setter that is sanitizing the values? Try logging the values that flow through these mappings.

**Comment by emobtech** [comment]
Thanks for the response. Just found out the issue was on my side. Awesome lib, btw. Thanks!
