### ISSUE TITLE
Too Many Arguments to Function Call

### ISSUE THREAD

**Issue by BFMarks** [Tricertops/Block-KVO#47]
Hey,

I'm running  Xcode Version 8.3.2, Objective-C and the Cocoapod:
pod 'Block-KVO', :git => 'https://github.com/Tricertops/Block-KVO.git'

The error is in NSObject+MTKObserving.m as shown by [this screenshot](https://www.evernote.com/l/ArGTGp0SY7tMkKjadN64pNvpekLKeSyq7_g)

Any work around?!  Please let me know :)

**Comment by BFMarks** [comment]
Also, pod --version
1.2.0

**Comment by Tricertops** [comment]
Use latest version.

**Comment by BFMarks** [comment]
It says: 

> CocoaPods central repositary will no longer be updated. Use this: pod 'Block-KVO', :git => 'https://github.com/Tricertops/Block-KVO.git'

Does that mean I have to manually import the libraries to get the latest version?
