### ISSUE TITLE
PodSpec Version

### ISSUE THREAD

**Issue by christiedavis** [Tricertops/Block-KVO#51]
The podspec in the git repository says version 3.0 but the one in coccoapods is still 2.2.1
https://cocoapods.org/pods/Block-KVO

In version 2.2.1 I am having issues building  with line 196 of NSObject+MTKObserving.m
I notice in version 3.0 (when downloaded from github) it is building. Are you able to check the version in cocoapods is up to date?

Thanks

**Comment by Tricertops** [comment]
Use the latest commit from `master` branch. I created tag v3.0 more than one year ago and fixed some things since then.

Every commit is a new 3.0.x version.
